Proyecto/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('docentes/', include('evaluaciones.urls')),
]

users/urls.py
from django.conf.urls import url
from users import views
from django.urls import path

# SET THE NAMESPACE!
app_name = 'users'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^login/$',views.user_login,name='user_login'),
    url(r'^register/$',views.register,name='register'),
    path('user_logout',views.user_logout,name='user_logout'),
    url(r'^principalUser/$',views.principalUser,name='principalUser'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from users.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

users/views.py
from django.shortcuts import render
from users.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'users/index.html')


@login_required
def special(request):
    return HttpResponse("Entraste al sistema !")


@login_required
def user_logout(request):
    if request.method == 'POST':
        logout(request)

        return render(request,'users/user_login')


@login_required
def principalUser(request):
    return render(request, 'users/principalUser.html')


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('Encontrado')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'users/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return render(request, 'users/principalUser.html')
            else:
                return HttpResponse("Tu cuenta esta inactiva.")
        else:
            print('Alguien ha intentado logearse y fallo')
            print("usaron el username: {} y la contraseña: {}".format(username, password))
            return HttpResponse("Datos erroneos para logearse")
    else:
        return render(request, 'users/login.html', {})

templates/users/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'users:user_login' %}">Users</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'users:user_logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'users:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/users/buscarAsignatura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Usuarios</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
<div class="container" style="padding-top: 5%">
    <h2>Asignaturas</h2>
    <p>Escribe para buscar por nombre de la asignatura o codigo de la misma</p>
    <input class="form-control" id="myInput" type="text" placeholder="Buscar asignatura . . . ">
    <br>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Codigo</th>
            <th>Nombre Asignatura</th>
            <th>Nro Creditos</th>
            <th>Docentes Encargados</th>
        </tr>
        </thead>
        <tbody id="myTable">
        {% for asignatura in asignaturas %}
            <tr>
                <td>{{ asignatura.codigo }}</td>
                <td>{{ asignatura.nombre }}</td>
                <td>{{ asignatura.creditos }}</td>
                <td>{{ asignatura.docentes }}</td>
                <td>
                    <a href="{% url 'edit' asignatura.id %}" class="btn btn-warning"><span class="fas fa-wrench"></span></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
        <a href="{% url 'user_logout' %}" class="btn btn-success">Salir</a>
    </div>
</div>
<script>
    $(document).ready(function(){
        $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
</body>
</html>

templates/users/buscarDocente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Docentes</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
<div class="container" style="padding-top: 5%">
    <h2>Docentes</h2>
    <p>Escribe para buscar por nombre o apellido del docente</p>
    <input class="form-control" id="myInput" type="text" placeholder="Buscar docente . . . ">
    <br>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Docente</th>
            <th>Asignaturas que dicta</th>
            <th>Agregar Comentario</th>
        </tr>
        </thead>
        <tbody id="myTable">
        {% for docente in docentes %}
            <tr>
                <td>{{ docente.nombre }}</td>
                <td>{{ docente.asignatura }}</td>
                <td>
                   <a href="{% url 'edit' docente.id %}" class="btn btn-warning"><span class="fas fa-wrench"></span></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">

    </div>
</div>
<script>
    $(document).ready(function(){
        $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
</body>
</html>

templates/users/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Añadir comentario</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <form method="POST" class="post-form" action="{% url 'update' docente.id %}">
            {% csrf_token %}
            <div class="container">
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                    <h3>Enviar un comentario</h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Docente:</label>
                    <div class="col-sm-4">
                        <input disabled class="form-control" type="text" value="{{ docente.nombre }}" />
                        <input type="hidden" name="nombre" value="{{ docente.nombre }}" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Asignatura:</label>
                    <div class="col-sm-4">
                        <input disabled class="form-control" type="text" value="{{ docente.asignatura }}" />
                        <input type="hidden" name="asignatura" value="{{ docente.asignatura }}" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-4">
                        <input type="text" name="comentarios" required value="{{ docente.comentarios }}" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-success">Enviar</button>
                    </div>
                </div>
            </div>
        </form>
    </body>
</html>

templates/users/index.html
{% extends "users/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/users/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="/static/css/estilos.css">
    <link href="https://fonts.googleapis.com/css?family-Oswald" rel="stylesheet">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1">
</head>
<body>
    <div class="login-box">
        <img class="login-img" src="/static/img/login_img.png">
        <h2 class="login-text">Log In</h2>
        <form method="post" action="{% url 'users:user_login' %}">
            {% csrf_token %}
            {# A more "HTML" way of creating the login form#}
            <fieldset>
                <p>Username</p>
                <input type="text" name="username" placeholder="Username">
                <p>Password</p>
                <input type="password" name="password" placeholder="Password">
                <input class="btn-login" type="submit" name="" value="Login">
            </fieldset>

        </form>
        <form method="post" action="{% url 'users:register' %}">
            {% csrf_token %}
            <fieldset>
                <input class="btn-registrar" type="submit" name="" value="Register">
            </fieldset>
        </form>
    </div>
</body>
</html>

templates/users/principalUser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bienvenido {{ user.username }}</title>
    <link rel="stylesheet" href="/static/css/estilos.css">
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
            {{ request.user }} | <a href="#" onClick="document.getElementById('logoutform').submit()"><button type="button">Logout</button></a>
            <form id="logoutform" method="POST" action="{% url 'users:user_logout' %}">
                {% csrf_token %}
                <input type="hidden">
            </form>
        </ul>
      </div>
    </nav>

    <div>
        <form class="botones">
            {% csrf_token %}
            <a href="{% url 'show' %}" class="btn-docente">Buscar Docente</a>
            <a href="{% url 'formulario' %}" class="btn-asignatura">Buscar Asignatura</a>
        </form>
    </div>
</body>
</html>

templates/users/registration.html
{% extends "users/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}